#!/usr/bin/env node
/**
 * run/generate.js
 *
 * Dynamically fetches every tree-sitter grammar npm package, builds WASM,
 * and emits a self-decoding ES module into ./main/<lang>.js
 *
 * Usage:
 *   node run/generate.js              # build all
 *   node run/generate.js python rust  # build specific langs only
 */

const { execSync, spawnSync } = require("child_process")
const fs   = require("fs")
const path = require("path")
const os   = require("os")

// ─── Grammar registry ────────────────────────────────────────────────────────
const GRAMMARS = [
  { lang: "bash",        npm: "tree-sitter-bash"        },
  { lang: "c",           npm: "tree-sitter-c"           },
  { lang: "cpp",         npm: "tree-sitter-cpp"         },
  { lang: "c-sharp",     npm: "tree-sitter-c-sharp"     },
  { lang: "css",         npm: "tree-sitter-css"         },
  { lang: "dockerfile",  npm: "tree-sitter-dockerfile"  },
  { lang: "elisp",       npm: "tree-sitter-elisp"       },
  { lang: "go",          npm: "tree-sitter-go"          },
  { lang: "haskell",     npm: "tree-sitter-haskell"     },
  { lang: "html",        npm: "tree-sitter-html"        },
  { lang: "java",        npm: "tree-sitter-java"        },
  { lang: "javascript",  npm: "tree-sitter-javascript"  },
  { lang: "json",        npm: "tree-sitter-json"        },
  { lang: "julia",       npm: "tree-sitter-julia"       },
  { lang: "kotlin",      npm: "tree-sitter-kotlin"      },
  { lang: "lua",         npm: "tree-sitter-lua"         },
  { lang: "markdown",    npm: "tree-sitter-markdown"    },
  { lang: "nix",         npm: "tree-sitter-nix"         },
  { lang: "ocaml",       npm: "tree-sitter-ocaml"       },
  { lang: "php",         npm: "tree-sitter-php"         },
  { lang: "python",      npm: "tree-sitter-python"      },
  { lang: "r",           npm: "tree-sitter-r"           },
  { lang: "ruby",        npm: "tree-sitter-ruby"        },
  { lang: "rust",        npm: "tree-sitter-rust"        },
  { lang: "scala",       npm: "tree-sitter-scala"       },
  { lang: "sql",         npm: "tree-sitter-sql"         },
  { lang: "swift",       npm: "tree-sitter-swift"       },
  { lang: "toml",        npm: "tree-sitter-toml"        },
  { lang: "tsx",         npm: "tree-sitter-typescript"  },
  { lang: "typescript",  npm: "tree-sitter-typescript"  },
  { lang: "yaml",        npm: "tree-sitter-yaml"        },
  { lang: "zig",         npm: "tree-sitter-zig"         },
]

// ─── Helpers ─────────────────────────────────────────────────────────────────

function toCamelCase(str) {
  return str.replace(/-([a-z])/g, (_, c) => c.toUpperCase())
}

function sh(cmd, cwd) {
  return spawnSync(cmd, { cwd, shell: true, stdio: "inherit" })
}

function shSilent(cmd, cwd) {
  return spawnSync(cmd, { cwd, shell: true, stdio: "pipe" })
}

function gitHead(dir) {
  try { return execSync("git rev-parse HEAD", { cwd: dir }).toString().trim() }
  catch { return "main" }
}

/** Find the tree-sitter CLI binary installed inside tmpDir */
function findCli(tmpDir) {
  // npm puts binaries in node_modules/.bin/
  const bin = path.join(tmpDir, "node_modules", ".bin", "tree-sitter")
  if (fs.existsSync(bin)) return bin

  // fallback: walk node_modules/tree-sitter-cli looking for the native binary
  const cliPkg = path.join(tmpDir, "node_modules", "tree-sitter-cli")
  if (!fs.existsSync(cliPkg)) return null

  // the prebuilt binary lives at the package root, named just "tree-sitter"
  // (or "tree-sitter.exe" on Windows)
  const exe = process.platform === "win32" ? "tree-sitter.exe" : "tree-sitter"
  for (const entry of fs.readdirSync(cliPkg, { withFileTypes: true })) {
    if (entry.name === exe) return path.join(cliPkg, exe)
  }

  return null
}

/** Recursively find first .wasm matching hint, else any .wasm */
function findWasm(dir, hint) {
  const preferred = `tree-sitter-${hint}.wasm`
  const walk = (d) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, e.name)
      if (e.isFile() && e.name === preferred) return full
      if (e.isFile() && e.name.endsWith(".wasm")) return full  // keep as fallback
      // don't recurse into node_modules
      if (e.isDirectory() && e.name !== "node_modules") {
        const r = walk(full)
        if (r && r.endsWith(preferred)) return r
      }
    }
    // second pass: return any .wasm if preferred not found
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, e.name)
      if (e.isFile() && e.name.endsWith(".wasm")) return full
      if (e.isDirectory() && e.name !== "node_modules") {
        const r = walk(full)
        if (r) return r
      }
    }
    return null
  }
  return walk(dir)
}

/** Emit a self-decoding ES module from raw wasm bytes */
function emitJs(buf, lang) {
  const b64 = buf.toString("base64")
  return [
    `// Generated Tree-sitter WASM bundle — ${lang}`,
    `// Auto-generated by run/generate.js — do not edit`,
    `const b64 = "${b64}";`,
    `const decode = typeof atob !== "undefined"`,
    `  ? (s) => atob(s)`,
    `  : (s) => Buffer.from(s, "base64").toString("binary");`,
    `const bytes = Uint8Array.from(decode(b64), c => c.charCodeAt(0));`,
    `export default bytes;`,
    `export { bytes };`,
    "",
  ].join("\n")
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  const filterArgs = process.argv.slice(2)
  const targets = filterArgs.length
    ? GRAMMARS.filter(g => filterArgs.includes(g.lang))
    : GRAMMARS

  if (!targets.length) {
    console.error("No matching grammars found for:", filterArgs)
    process.exit(1)
  }

  const rootDir = path.resolve(__dirname, "..")
  const mainDir = path.join(rootDir, "main")
  if (!fs.existsSync(mainDir)) fs.mkdirSync(mainDir, { recursive: true })

  const commitHash = gitHead(rootDir)

  const uniqueNpm = [...new Set(targets.map(g => g.npm))]

  // ── 1. Set up temp workspace ───────────────────────────────────────────────
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "ts-grammars-"))
  console.log(`\n📦 Installing into ${tmpDir} …\n`)

  fs.writeFileSync(
    path.join(tmpDir, "package.json"),
    JSON.stringify({ name: "ts-build-tmp", version: "0.0.0", private: true }, null, 2)
  )

  // Step 1: install tree-sitter-cli WITH scripts so its postinstall
  // downloads the prebuilt binary
  console.log("   Installing tree-sitter-cli …")
  const cliRes = sh(
    `npm install --no-save --legacy-peer-deps tree-sitter-cli`,
    tmpDir
  )
  if (cliRes.status !== 0) {
    console.error("❌ tree-sitter-cli install failed")
    fs.rmSync(tmpDir, { recursive: true, force: true })
    process.exit(1)
  }

  // Step 2: install grammar packages with --ignore-scripts to skip node-gyp
  // (we only need the grammar source files, not native Node bindings)
  console.log(`   Installing ${uniqueNpm.length} grammar package(s) …`)
  const grammarRes = sh(
    `npm install --no-save --legacy-peer-deps --ignore-scripts ${uniqueNpm.join(" ")}`,
    tmpDir
  )
  if (grammarRes.status !== 0) {
    console.error("❌ grammar install failed")
    fs.rmSync(tmpDir, { recursive: true, force: true })
    process.exit(1)
  }

  // ── 2. Resolve the CLI binary ──────────────────────────────────────────────
  const cliBin = findCli(tmpDir)
  if (!cliBin) {
    console.error("❌ Could not find tree-sitter binary after install")
    console.error("   Looked in:", path.join(tmpDir, "node_modules", ".bin"))
    fs.rmSync(tmpDir, { recursive: true, force: true })
    process.exit(1)
  }
  // Ensure it's executable (matters on Linux/macOS)
  try { fs.chmodSync(cliBin, 0o755) } catch {}
  console.log(`\n✅ CLI binary: ${cliBin}\n`)

  // ── 3. Build each grammar ──────────────────────────────────────────────────
  const results = { ok: [], failed: [] }

  for (const { lang, npm } of targets) {
    console.log(`${"─".repeat(60)}`)
    console.log(`🔨 ${lang}  (${npm})`)

    const pkgDir = path.join(tmpDir, "node_modules", npm)
    if (!fs.existsSync(pkgDir)) {
      console.error(`   ❌ Package dir not found: ${pkgDir}`)
      results.failed.push({ lang, reason: "package dir missing" })
      continue
    }

    // Handle sub-grammar dirs (e.g. tree-sitter-typescript/tsx)
    const npmBase  = npm.replace(/^tree-sitter-/, "")
    const buildDir = (lang !== npmBase && fs.existsSync(path.join(pkgDir, lang)))
      ? path.join(pkgDir, lang)
      : pkgDir

    console.log(`   cwd: ${buildDir}`)

    // Run: <cliBin> build --wasm
    // Use shell:false here — we have the exact path, no shell expansion needed
    const buildRes = spawnSync(cliBin, ["build", "--wasm"], {
      cwd: buildDir,
      stdio: "inherit",
      // tree-sitter build --wasm needs to find emcc; inherit the full env
      env: process.env,
    })

    if (buildRes.status !== 0) {
      console.error(`   ❌ Build failed (exit ${buildRes.status})`)
      if (buildRes.error) console.error(`   `, buildRes.error.message)
      results.failed.push({ lang, reason: `exit ${buildRes.status}` })
      continue
    }

    const wasmPath = findWasm(buildDir, lang)
    if (!wasmPath) {
      console.error(`   ❌ No .wasm found after build in ${buildDir}`)
      results.failed.push({ lang, reason: "wasm not found" })
      continue
    }

    const buf    = fs.readFileSync(wasmPath)
    const outJs  = path.join(mainDir, `${lang}.js`)
    fs.writeFileSync(outJs, emitJs(buf, lang))

    console.log(`   ✅ main/${lang}.js  (${(buf.length / 1024).toFixed(0)} KB)`)
    console.log(`   🔗 import ${toCamelCase(lang)} from "https://github.com/jeff-hykin/common_tree_sitter_languages/raw/${commitHash}/main/${lang}.js"`)
    results.ok.push(lang)
  }

  // ── 4. Cleanup ─────────────────────────────────────────────────────────────
  console.log(`\n${"─".repeat(60)}`)
  console.log("🧹 Cleaning up …")
  fs.rmSync(tmpDir, { recursive: true, force: true })

  // ── 5. Summary ─────────────────────────────────────────────────────────────
  console.log(`\n${"═".repeat(60)}`)
  console.log(`✅ Built (${results.ok.length}): ${results.ok.join(", ") || "none"}`)
  if (results.failed.length) {
    console.log(`❌ Failed (${results.failed.length}):`)
    for (const { lang, reason } of results.failed) {
      console.log(`   • ${lang}: ${reason}`)
    }
    process.exit(1)
  }
  console.log(`${"═".repeat(60)}\n`)
}

main().catch(err => {
  console.error("Unexpected error:", err)
  process.exit(1)
})
