#!/usr/bin/env node
/**
 * build-parsers.js
 *
 * Installs tree-sitter grammar npm packages, grabs their pre-built .wasm
 * files, and emits self-decoding ES modules into ./main/<lang>.js
 *
 * Falls back to `tree-sitter build --wasm` for packages without pre-built
 * wasm (requires Emscripten on PATH for those).
 *
 * Usage:
 *   node build-parsers.js              # build all
 *   node build-parsers.js python rust  # specific langs only
 */

const { execSync, spawnSync } = require("child_process")
const fs   = require("fs")
const path = require("path")
const os   = require("os")

// ─── Grammar registry ────────────────────────────────────────────────────────
// `alts`: fallback npm packages tried in order when the primary has no
// pre-built wasm AND fails to build (e.g. wasm-incompatible external scanner).
const GRAMMARS = [
  { lang: "bash",        npm: "tree-sitter-bash"        },
  { lang: "c",           npm: "tree-sitter-c"           },
  { lang: "cpp",         npm: "tree-sitter-cpp"         },
  { lang: "c-sharp",     npm: "tree-sitter-c-sharp"     },
  { lang: "css",         npm: "tree-sitter-css"         },
  { lang: "dockerfile",  npm: "tree-sitter-dockerfile"  },
  { lang: "elisp",       npm: "tree-sitter-elisp"       },
  { lang: "go",          npm: "tree-sitter-go"          },
  { lang: "haskell",     npm: "tree-sitter-haskell"     },
  { lang: "html",        npm: "tree-sitter-html"        },
  { lang: "java",        npm: "tree-sitter-java"        },
  { lang: "javascript",  npm: "tree-sitter-javascript"  },
  { lang: "json",        npm: "tree-sitter-json"        },
  { lang: "julia",       npm: "tree-sitter-julia"       },
  { lang: "kotlin",      npm: "tree-sitter-kotlin"      },
  { lang: "lua",         npm: "tree-sitter-lua"         },
  { lang: "markdown",    npm: "tree-sitter-markdown"    },
  { lang: "nix",         npm: "tree-sitter-nix"         },
  { lang: "ocaml",       npm: "tree-sitter-ocaml"       },
  { lang: "php",         npm: "tree-sitter-php"         },
  { lang: "python",      npm: "tree-sitter-python"      },
  { lang: "r",           npm: "tree-sitter-r"           },
  { lang: "ruby",        npm: "tree-sitter-ruby"        },
  { lang: "rust",        npm: "tree-sitter-rust"        },
  { lang: "scala",       npm: "tree-sitter-scala"       },
  { lang: "sql",         npm: "tree-sitter-sql"         },
  { lang: "swift",       npm: "tree-sitter-swift"       },
  { lang: "toml",        npm: "tree-sitter-toml"        },
  { lang: "tsx",         npm: "tree-sitter-typescript"  },
  { lang: "typescript",  npm: "tree-sitter-typescript"  },
  // tree-sitter-yaml's external scanner is wasm-incompatible; use the
  // community fork that ships a pre-built wasm instead.
  { lang: "yaml",        npm: "tree-sitter-yaml", alts: ["@nickel-org/tree-sitter-yaml"] },
  { lang: "zig",         npm: "tree-sitter-zig"         },
]

// Sentinel string present in tree-sitter's stderr when a grammar's external
// scanner uses C symbols that can never work in a WASM sandbox.
const WASM_INCOMPATIBLE_MSG = "isn't available to Wasm parsers"

// ─── Helpers ─────────────────────────────────────────────────────────────────

function toCamelCase(str) {
  return str.replace(/-([a-z])/g, (_, c) => c.toUpperCase())
}

function sh(cmd, cwd) {
  return spawnSync(cmd, { cwd, shell: true, stdio: "inherit" })
}

function gitHead(dir) {
  try { return execSync("git rev-parse HEAD", { cwd: dir }).toString().trim() }
  catch { return "main" }
}

function makeTmp(prefix) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix))
  fs.writeFileSync(
    path.join(dir, "package.json"),
    JSON.stringify({ name: prefix.replace(/-$/, ""), version: "0.0.0", private: true }, null, 2)
  )
  return dir
}

/**
 * Recursively find a .wasm file under dir (skipping node_modules).
 * Prefers tree-sitter-<hint>.wasm, returns any .wasm as fallback.
 */
function findWasm(dir, hint) {
  const preferred = `tree-sitter-${hint}.wasm`
  let fallback = null

  function walk(d, depth = 0) {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, e.name)
      if (e.isFile()) {
        if (e.name === preferred)     return full
        if (e.name.endsWith(".wasm")) fallback = fallback ?? full
      } else if (e.isDirectory() && depth < 3 && e.name !== "node_modules") {
        const r = walk(full, depth + 1)
        if (r) return r
      }
    }
    return null
  }

  return walk(dir) ?? fallback
}

/** Emit a self-decoding ES module — consumers get a Uint8Array of wasm bytes */
function emitJs(buf, lang) {
  const b64 = buf.toString("base64")
  return [
    `// Generated Tree-sitter WASM bundle — ${lang}`,
    `// Auto-generated by build-parsers.js — do not edit`,
    `const b64 = "${b64}";`,
    `const decode = typeof atob !== "undefined"`,
    `  ? (s) => atob(s)`,
    `  : (s) => Buffer.from(s, "base64").toString("binary");`,
    `const bytes = Uint8Array.from(decode(b64), c => c.charCodeAt(0));`,
    `export default bytes;`,
    `export { bytes };`,
    "",
  ].join("\n")
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  const filterArgs = process.argv.slice(2)
  const targets = filterArgs.length
    ? GRAMMARS.filter(g => filterArgs.includes(g.lang))
    : GRAMMARS

  if (!targets.length) {
    console.error("No matching grammars for:", filterArgs)
    process.exit(1)
  }

  const rootDir = path.resolve(__dirname)
  const mainDir = path.join(rootDir, "main")
  if (!fs.existsSync(mainDir)) fs.mkdirSync(mainDir, { recursive: true })

  const commitHash = gitHead(rootDir)
  const uniqueNpm  = [...new Set(targets.map(g => g.npm))]

  // ── 1. Install tree-sitter-cli into its OWN isolated dir ─────────────────
  //    Keeping it separate prevents npm from removing grammar packages when
  //    it re-resolves peer deps during a mixed install.
  const cliDir = makeTmp("ts-cli-")
  console.log(`\n🔧 Installing tree-sitter-cli into ${cliDir} …`)
  const cliRes = sh(`npm install --no-save tree-sitter-cli`, cliDir)
  if (cliRes.status !== 0) {
    console.error("❌ tree-sitter-cli install failed — fallback builds won't work")
    // non-fatal: grammars with pre-built wasm will still succeed
  }

  const cliBinName = process.platform === "win32" ? "tree-sitter.cmd" : "tree-sitter"
  const cliBin = path.join(cliDir, "node_modules", ".bin", cliBinName)
  const cliAvailable = fs.existsSync(cliBin)
  if (cliAvailable) {
    try { fs.chmodSync(cliBin, 0o755) } catch {}
    console.log(`   ✅ CLI binary: ${cliBin}\n`)
  } else {
    console.warn(`   ⚠️  CLI binary not found — packages without pre-built wasm will fail\n`)
  }

  // ── 2. Install grammars in their own isolated dir (--ignore-scripts) ──────
  const grammarDir = makeTmp("ts-grammars-")
  console.log(`📦 Installing ${uniqueNpm.length} grammar package(s) into ${grammarDir} …\n`)

  const grammarRes = sh(
    `npm install --no-save --legacy-peer-deps --ignore-scripts ${uniqueNpm.join(" ")}`,
    grammarDir
  )
  if (grammarRes.status !== 0) {
    console.error("❌ grammar install failed")
    fs.rmSync(cliDir,     { recursive: true, force: true })
    fs.rmSync(grammarDir, { recursive: true, force: true })
    process.exit(1)
  }

  // ── 3. Process each grammar ───────────────────────────────────────────────
  const results = { ok: [], builtFromSource: [], failed: [] }

  for (const { lang, npm, alts = [] } of targets) {
    console.log(`${"─".repeat(60)}`)
    console.log(`🔍 ${lang}  (${npm})`)

    // Helper: resolve pkg dir + optional sub-grammar dir for any npm package
    const resolveDirs = (pkgName) => {
      const pkgDir = path.join(grammarDir, "node_modules", pkgName)
      if (!fs.existsSync(pkgDir)) return null
      const base     = pkgName.replace(/^(@[^/]+\/)?tree-sitter-/, "")
      const buildDir = (lang !== base && fs.existsSync(path.join(pkgDir, lang)))
        ? path.join(pkgDir, lang)
        : pkgDir
      return { pkgDir, buildDir }
    }

    // Helper: attempt one build-from-source, returns { wasmPath, wasmIncompat }
    const tryBuild = (buildDir) => {
      if (!cliAvailable) return { wasmPath: null, wasmIncompat: false }
      const res = spawnSync(cliBin, ["build", "--wasm"], {
        cwd: buildDir,
        stdio: ["inherit", "inherit", "pipe"],  // capture stderr for error detection
        env: process.env,
      })
      const stderr = res.stderr?.toString() ?? ""
      process.stderr.write(stderr)  // still show it
      const wasmIncompat = stderr.includes(WASM_INCOMPATIBLE_MSG)
      if (res.status !== 0 || res.signal) return { wasmPath: null, wasmIncompat }
      return { wasmPath: findWasm(buildDir, lang), wasmIncompat: false }
    }

    let wasmPath   = null
    let usedPkg    = npm
    let fromSource = false

    // ── 1. Try primary package ────────────────────────────────────────────
    const primary = resolveDirs(npm)
    if (!primary) {
      console.error(`   ❌ Package dir not found`)
      results.failed.push({ lang, reason: "package dir missing" })
      continue
    }

    wasmPath = findWasm(primary.buildDir, lang)
    if (!wasmPath && primary.buildDir !== primary.pkgDir)
      wasmPath = findWasm(primary.pkgDir, lang)

    if (wasmPath) {
      console.log(`   ✅ Pre-built wasm found`)
    } else {
      console.log(`   ⚙️  No pre-built wasm — building from source …`)
      const built = tryBuild(primary.buildDir)
      wasmPath    = built.wasmPath
      fromSource  = !!wasmPath

      // ── 2. If wasm-incompatible scanner, try alt packages ─────────────
      if (!wasmPath && built.wasmIncompat && alts.length) {
        console.warn(`   ⚠️  Wasm-incompatible external scanner — trying alternatives …`)

        // install all alts at once into the grammar workspace
        const toInstall = alts.filter(a => !fs.existsSync(path.join(grammarDir, "node_modules", a)))
        if (toInstall.length) {
          sh(`npm install --no-save --legacy-peer-deps --ignore-scripts ${toInstall.join(" ")}`, grammarDir)
        }

        for (const alt of alts) {
          console.log(`   🔄 Trying alt: ${alt}`)
          const altDirs = resolveDirs(alt)
          if (!altDirs) { console.warn(`      ⚠️  Not found after install`); continue }

          wasmPath = findWasm(altDirs.buildDir, lang)
          if (!wasmPath && altDirs.buildDir !== altDirs.pkgDir)
            wasmPath = findWasm(altDirs.pkgDir, lang)

          if (wasmPath) {
            console.log(`      ✅ Pre-built wasm found in ${alt}`)
            usedPkg = alt; break
          }

          const altBuilt = tryBuild(altDirs.buildDir)
          if (altBuilt.wasmPath) {
            wasmPath   = altBuilt.wasmPath
            fromSource = true
            usedPkg    = alt
            break
          }
        }
      }

      if (!wasmPath) {
        const why = built.wasmIncompat
          ? "wasm-incompatible external scanner, no working alt"
          : `build failed`
        console.error(`   ❌ ${why}`)
        results.failed.push({ lang, reason: why })
        continue
      }
    }

    // ── Emit JS bundle ────────────────────────────────────────────────────
    const buf   = fs.readFileSync(wasmPath)
    const outJs = path.join(mainDir, `${lang}.js`)
    fs.writeFileSync(outJs, emitJs(buf, lang))

    const pkgNote = usedPkg !== npm ? ` (via ${usedPkg})` : ""
    console.log(`   📦 main/${lang}.js  (${(buf.length / 1024).toFixed(0)} KB)${pkgNote}`)
    console.log(`   🔗 import ${toCamelCase(lang)} from "https://github.com/jeff-hykin/common_tree_sitter_languages/raw/${commitHash}/main/${lang}.js"`)
    if (fromSource) results.builtFromSource.push(lang)
    results.ok.push(lang)
  }

  // ── 4. Cleanup ─────────────────────────────────────────────────────────────
  console.log(`\n${"─".repeat(60)}`)
  console.log("🧹 Cleaning up …")
  fs.rmSync(cliDir,     { recursive: true, force: true })
  fs.rmSync(grammarDir, { recursive: true, force: true })

  // ── 5. Summary ─────────────────────────────────────────────────────────────
  console.log(`\n${"═".repeat(60)}`)
  console.log(`✅ Built (${results.ok.length}): ${results.ok.join(", ") || "none"}`)
  if (results.builtFromSource.length)
    console.log(`⚙️  From source: ${results.builtFromSource.join(", ")}`)
  if (results.failed.length) {
    console.log(`❌ Failed (${results.failed.length}):`)
    for (const { lang, reason } of results.failed)
      console.log(`   • ${lang}: ${reason}`)
    process.exit(1)
  }
  console.log(`${"═".repeat(60)}\n`)
}

main().catch(err => {
  console.error("Unexpected error:", err)
  //process.exit(1)
   process.exit()
})
